-- NBeauty fresh PostgreSQL init.
-- Source of truth: /Users/nic_piter/Desktop/nbeauty_dump_last.sql

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS nbeauty;
GRANT ALL ON SCHEMA nbeauty TO CURRENT_USER;
ALTER DATABASE postgres SET search_path TO nbeauty, public;
SET search_path TO nbeauty, public;

CREATE OR REPLACE FUNCTION nbeauty.generate_invite_code()
RETURNS varchar
LANGUAGE plpgsql
AS $$
DECLARE
    chars text := '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    result text := '';
    i integer;
BEGIN
    FOR i IN 1..24 LOOP
        result := result || substring(chars FROM ceil(random() * 62)::int FOR 1);
    END LOOP;

    RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION nbeauty.regenerate_salon_invite_code(p_salon_id uuid)
RETURNS varchar
LANGUAGE plpgsql
AS $$
DECLARE
    new_code varchar(24);
BEGIN
    PERFORM 1 FROM nbeauty.salons WHERE id = p_salon_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Салон с ID % не найден', p_salon_id;
    END IF;

    new_code := nbeauty.generate_invite_code();

    UPDATE nbeauty.salons
    SET invite_code = new_code,
        updated_at = now()
    WHERE id = p_salon_id;

    RETURN new_code;
END;
$$;

CREATE OR REPLACE FUNCTION nbeauty.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION nbeauty.trigger_generate_invite_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.invite_code IS NULL OR btrim(NEW.invite_code) = '' THEN
        NEW.invite_code := nbeauty.generate_invite_code();
    END IF;

    RETURN NEW;
END;
$$;

CREATE TABLE nbeauty.users (
    tg_id bigint NOT NULL,
    full_name varchar(255) NOT NULL,
    username varchar(255),
    role varchar(32) DEFAULT 'client'::varchar NOT NULL,
    avatar varchar(255),
    specialty varchar(255),
    rating numeric(3,2) DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    telephone_number VARCHAR(32),
    CONSTRAINT chk_users_rating CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT users_role_check CHECK (role IN ('client', 'master')),
    CONSTRAINT users_pkey PRIMARY KEY (tg_id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE nbeauty.platform_admins (
    user_id bigint NOT NULL,
    granted_by bigint,
    granted_at timestamptz DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT platform_admins_pkey PRIMARY KEY (user_id),
    CONSTRAINT platform_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE,
    CONSTRAINT platform_admins_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES nbeauty.users(tg_id) ON DELETE SET NULL
);

CREATE TABLE nbeauty.salons (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name varchar(255) NOT NULL,
    owner_id bigint NOT NULL,
    invite_code varchar(255) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT salons_pkey PRIMARY KEY (id),
    CONSTRAINT salons_invite_code_key UNIQUE (invite_code),
    CONSTRAINT salons_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE
);

CREATE TABLE nbeauty.salon_members (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    salon_id uuid NOT NULL,
    user_id bigint NOT NULL,
    role varchar(32) DEFAULT 'master'::varchar NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT salon_members_pkey PRIMARY KEY (id),
    CONSTRAINT salon_members_role_check CHECK (role IN ('admin', 'master')),
    CONSTRAINT uq_salon_members_salon_user UNIQUE (salon_id, user_id),
    CONSTRAINT salon_members_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES nbeauty.salons(id) ON DELETE CASCADE,
    CONSTRAINT salon_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE
);

CREATE TABLE nbeauty.resources (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salon_id uuid NOT NULL,
    name varchar(255) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT resources_pkey PRIMARY KEY (id),
    CONSTRAINT uq_resources_salon_name UNIQUE (salon_id, name),
    CONSTRAINT resources_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES nbeauty.salons(id) ON DELETE CASCADE
);

CREATE TABLE nbeauty.services (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    master_id bigint NOT NULL,
    salon_id uuid,
    resource_id integer,
    name varchar(255) NOT NULL,
    duration integer NOT NULL,
    price integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT services_pkey PRIMARY KEY (id),
    CONSTRAINT chk_services_duration_positive CHECK (duration > 0),
    CONSTRAINT chk_services_price_non_negative CHECK (price >= 0),
    CONSTRAINT services_master_id_fkey FOREIGN KEY (master_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE,
    CONSTRAINT services_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES nbeauty.salons(id) ON DELETE SET NULL,
    CONSTRAINT services_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES nbeauty.resources(id) ON DELETE SET NULL
);

CREATE TABLE nbeauty.master_schedules (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    master_id bigint NOT NULL,
    salon_id uuid,
    day_of_week integer NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    CONSTRAINT master_schedules_pkey PRIMARY KEY (id),
    CONSTRAINT chk_master_schedules_day CHECK (day_of_week >= 0 AND day_of_week <= 6),
    CONSTRAINT chk_master_schedules_time CHECK (start_time < end_time),
    CONSTRAINT uq_master_schedules_master_salon_day UNIQUE (master_id, salon_id, day_of_week),
    CONSTRAINT master_schedules_master_id_fkey FOREIGN KEY (master_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE,
    CONSTRAINT master_schedules_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES nbeauty.salons(id) ON DELETE CASCADE
);

CREATE TABLE nbeauty.guest_clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    master_id bigint NOT NULL,
    full_name varchar(255) NOT NULL,
    telephone_number varchar(32) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT guest_clients_pkey PRIMARY KEY (id),
    CONSTRAINT uq_guest_clients_master_phone UNIQUE (master_id, telephone_number),
    CONSTRAINT guest_clients_master_id_fkey FOREIGN KEY (master_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE
);

CREATE INDEX idx_guest_clients_master_id
    ON nbeauty.guest_clients (master_id);

CREATE INDEX idx_guest_clients_telephone_number
    ON nbeauty.guest_clients (telephone_number);

CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_clients_master_phone
    ON nbeauty.guest_clients(master_id, telephone_number);

CREATE TABLE nbeauty.client_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    master_id bigint NOT NULL,
    client_id bigint,
    guest_client_id bigint,
    note text NOT NULL DEFAULT '',
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,

    CONSTRAINT client_notes_pkey PRIMARY KEY (id),

    CONSTRAINT client_notes_master_id_fkey
        FOREIGN KEY (master_id)
        REFERENCES nbeauty.users(tg_id)
        ON DELETE CASCADE,

    CONSTRAINT client_notes_client_id_fkey
        FOREIGN KEY (client_id)
        REFERENCES nbeauty.users(tg_id)
        ON DELETE CASCADE,

    CONSTRAINT client_notes_guest_client_id_fkey
        FOREIGN KEY (guest_client_id)
        REFERENCES nbeauty.guest_clients(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_client_notes_client_or_guest CHECK (
        (client_id IS NOT NULL AND guest_client_id IS NULL)
        OR
        (client_id IS NULL AND guest_client_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX ux_client_notes_master_client
ON nbeauty.client_notes(master_id, client_id)
WHERE client_id IS NOT NULL;


CREATE UNIQUE INDEX ux_client_notes_master_guest_client
ON nbeauty.client_notes(master_id, guest_client_id)
WHERE guest_client_id IS NOT NULL;


CREATE INDEX idx_client_notes_master_id
ON nbeauty.client_notes(master_id);

CREATE TABLE nbeauty.appointments (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    salon_id uuid,
    master_id bigint NOT NULL,
    client_id bigint,
    guest_client_id bigint,
    resource_id integer,
    service_id integer NOT NULL,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    status varchar(32) DEFAULT 'pending'::varchar NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT appointments_pkey PRIMARY KEY (id),
    CONSTRAINT appointments_status_check CHECK (status IN ('pending', 'confirmed', 'upcoming', 'cancelled', 'completed')),
    CONSTRAINT chk_appointments_time CHECK (start_time < end_time),
    CONSTRAINT appointments_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES nbeauty.salons(id) ON DELETE SET NULL,
    CONSTRAINT appointments_master_id_fkey FOREIGN KEY (master_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE,
    CONSTRAINT appointments_client_id_fkey FOREIGN KEY (client_id) REFERENCES nbeauty.users(tg_id) ON DELETE CASCADE,
    CONSTRAINT appointments_guest_client_id_fkey FOREIGN KEY (guest_client_id) REFERENCES nbeauty.guest_clients(id) ON DELETE SET NULL,
    CONSTRAINT appointments_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES nbeauty.resources(id) ON DELETE SET NULL,
    CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES nbeauty.services(id) ON DELETE RESTRICT,
    CONSTRAINT chk_appointments_client_or_guest
    CHECK (
    NOT (client_id IS NOT NULL AND guest_client_id IS NOT NULL)
    )
);

CREATE TABLE nbeauty.reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_id integer NOT NULL,
    rating integer NOT NULL,
    comment varchar(1000),
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id),
    CONSTRAINT reviews_appointment_id_key UNIQUE (appointment_id),
    CONSTRAINT chk_reviews_rating CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT reviews_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES nbeauty.appointments(id) ON DELETE CASCADE
);

CREATE TABLE nbeauty.telegram_login_sessions (
    token varchar(64) NOT NULL,
    status varchar(32) DEFAULT 'pending'::varchar NOT NULL,
    user_id bigint,
    created_at timestamptz DEFAULT now() NOT NULL,
    expires_at timestamptz NOT NULL,
    completed_at timestamptz,
    CONSTRAINT telegram_login_sessions_pkey PRIMARY KEY (token),
    CONSTRAINT telegram_login_sessions_status_check CHECK (status IN ('pending', 'completed', 'expired')),
    CONSTRAINT telegram_login_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES nbeauty.users(tg_id) ON DELETE SET NULL
);

ALTER TABLE nbeauty.appointments
    ADD CONSTRAINT ex_appointments_master_time_overlap
    EXCLUDE USING gist (master_id WITH =, tstzrange(start_time, end_time, '[)') WITH &&)
    WHERE (status <> 'cancelled');

ALTER TABLE nbeauty.appointments
    ADD CONSTRAINT ex_appointments_resource_time_overlap
    EXCLUDE USING gist (resource_id WITH =, tstzrange(start_time, end_time, '[)') WITH &&)
    WHERE (resource_id IS NOT NULL AND status <> 'cancelled');

CREATE INDEX idx_telegram_login_sessions_status_expires_at
    ON nbeauty.telegram_login_sessions (status, expires_at);

CREATE INDEX idx_telegram_login_sessions_user_id
    ON nbeauty.telegram_login_sessions (user_id);

CREATE OR REPLACE FUNCTION nbeauty.recalculate_master_rating(p_master_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    avg_rating numeric(3,2);
BEGIN
    SELECT COALESCE(round(avg(r.rating)::numeric, 2), 0)
    INTO avg_rating
    FROM nbeauty.reviews r
    JOIN nbeauty.appointments a ON a.id = r.appointment_id
    JOIN nbeauty.services s ON s.id = a.service_id
    WHERE s.master_id = p_master_id;

    UPDATE nbeauty.users
    SET rating = avg_rating,
        updated_at = now()
    WHERE tg_id = p_master_id
      AND role = 'master';
END;
$$;

CREATE OR REPLACE FUNCTION nbeauty.trigger_recalculate_master_rating()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    old_master_id bigint;
    new_master_id bigint;
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT master_id INTO new_master_id FROM nbeauty.appointments WHERE id = NEW.appointment_id;
        PERFORM nbeauty.recalculate_master_rating(new_master_id);
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        SELECT master_id INTO old_master_id FROM nbeauty.appointments WHERE id = OLD.appointment_id;
        SELECT master_id INTO new_master_id FROM nbeauty.appointments WHERE id = NEW.appointment_id;

        IF old_master_id <> new_master_id THEN
            PERFORM nbeauty.recalculate_master_rating(old_master_id);
            PERFORM nbeauty.recalculate_master_rating(new_master_id);
        ELSE
            PERFORM nbeauty.recalculate_master_rating(new_master_id);
        END IF;

        RETURN NEW;
    END IF;

    IF TG_OP = 'DELETE' THEN
        SELECT master_id INTO old_master_id FROM nbeauty.appointments WHERE id = OLD.appointment_id;
        PERFORM nbeauty.recalculate_master_rating(old_master_id);
        RETURN OLD;
    END IF;

    RETURN NULL;
END;
$$;

CREATE TRIGGER trigger_appointments_updated_at
    BEFORE UPDATE ON nbeauty.appointments
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

CREATE TRIGGER trigger_resources_updated_at
    BEFORE UPDATE ON nbeauty.resources
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

CREATE TRIGGER trigger_reviews_recalculate_rating
    AFTER INSERT OR UPDATE OR DELETE ON nbeauty.reviews
    FOR EACH ROW EXECUTE FUNCTION nbeauty.trigger_recalculate_master_rating();

CREATE TRIGGER trigger_salons_invite_code
    BEFORE INSERT ON nbeauty.salons
    FOR EACH ROW EXECUTE FUNCTION nbeauty.trigger_generate_invite_code();

CREATE TRIGGER trigger_salons_updated_at
    BEFORE UPDATE ON nbeauty.salons
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

CREATE TRIGGER trigger_services_updated_at
    BEFORE UPDATE ON nbeauty.services
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

CREATE TRIGGER trigger_users_updated_at
    BEFORE UPDATE ON nbeauty.users
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

CREATE TRIGGER trigger_guest_clients_updated_at
    BEFORE UPDATE ON nbeauty.guest_clients
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

CREATE TRIGGER trigger_client_notes_updated_at
    BEFORE UPDATE ON nbeauty.client_notes
    FOR EACH ROW EXECUTE FUNCTION nbeauty.update_updated_at_column();

COMMENT ON TABLE nbeauty.users IS 'Пользователи Telegram. role определяет режим: мастер (оказывает услуги) или клиент (записывается)';
COMMENT ON TABLE nbeauty.platform_admins IS 'Глобальные администраторы всей платформы (не салона!)';
COMMENT ON TABLE nbeauty.salons IS 'Салоны/студии. Владелец автоматически получает роль admin в salon_members';
COMMENT ON TABLE nbeauty.salon_members IS 'Участники салона: admin (управляет) или master (работает)';
COMMENT ON TABLE nbeauty.resources IS 'Ресурсы салона: кабинеты, кресла, оборудование — могут бронироваться вместе с записью';
COMMENT ON TABLE nbeauty.services IS 'Услуги мастеров. price — для отображения клиенту (без финансовой логики)';
COMMENT ON TABLE nbeauty.master_schedules IS 'Рабочее расписание мастеров: дни недели и часы работы в салоне';
COMMENT ON TABLE nbeauty.appointments IS 'Записи клиентов к мастерам. status отслеживает жизненный цикл записи';
COMMENT ON TABLE nbeauty.reviews IS 'Отзывы клиентов о мастерах. Один отзыв = одна завершённая запись';
COMMENT ON TABLE nbeauty.guest_clients IS 'Незарегистрированные клиенты мастеров: клиенты без Telegram tg_id, добавленные мастером вручную';
COMMENT ON TABLE nbeauty.client_notes IS 'Личные заметки мастеров о зарегистрированных и незарегистрированных клиентах';